### ISSUE TITLE
simplify the naming

### ISSUE THREAD

**Issue by devmondo** [zewa666/aurelia-i18next#14]
having to always write ```i18next``` is not comfortable, why dont we change it to ```aurelia-translate```

**Comment by zewa666** [comment]
Yep will definitely be renamed when moving to an official repo, for now it has this strange name as it was intended to try out i18next. I'll keep this issue open just to not forget about it when moving the repo

**Comment by devmondo** [comment]
please move it as soon as possible, this is really awesome and simple code compared to angular-translate, kudo man :)

**Comment by Aaike** [comment]
the injected instance can really be stored as any name :
```javascript
import {I18N} from 'aurelia-i18next';

export class Test {
    static inject = [I18N];
    constructor(t) {
       this.t = t;
    }
}
```

so you can just this this.t.t("something"); , or whatever you want to name it

**Comment by devmondo** [comment]
@Aaike thanks man, this solves it :)
