### ISSUE TITLE
time frame new release

### ISSUE THREAD

**Issue by flieks** [zewa666/aurelia-i18next#28]
Hi @zewa666 

Do you have a rough estimate when this repo gets updated?
I don't know if it's worth waiting translating my app now or later (as later it will be easier)

you said on gitter:
`we're now focusing on getting the different Animator implementations live
but the next task is to bring the i18n plugin to an official repo and also work more on the docs
especially the mentioned updateTranslation task should hopefully be made much easier with some tricks we're trying out right now`

**Comment by zewa666** [comment]
I hope we should be able to get this going within 1-2 weeks. The first version won't include all the bells and whistles but will be a good start to get more feedback and response from the community. The last thing as mentioned above is to make the registration of translation methods easier, as this feels quite cumbersome as it is right now.

**Comment by flieks** [comment]
ok thanks zewa,
i will maybe wait a week or 2
