### ISSUE TITLE
Sign Aurelia CLA for move to official plugin

### ISSUE THREAD

**Issue by zewa666** [zewa666/aurelia-i18next#30]
Dear @qlayer, @benjiro 

This repo will soon be ported over to an official aurelia repo. According to the code of contribution i'd like to ask you to sign the [official CLA](https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1) - [here is more info](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md) about it - so that we're allowed to reuse your contributions.

Thank you all for your great help so far

**Comment by benjiro** [comment]
Signed!

**Comment by qlayer** [comment]
Signed

**Comment by zewa666** [comment]
Thanks guys
