### ISSUE TITLE
Please use releases or branches when switching platform versions

### ISSUE THREAD

**Issue by jadrake75** [zewa666/aurelia-i18next#33]
I discovered very late tonight (1:20am my time) my app was not working because my use of the aurelia-i18next pulled in your update for the latest aurelia framework version.  While I intend to update I had not intended to do it until later in the week.  Without versions/tags/releases we can not fix config.json/package.json to look at a version while you iterate the library further.....

Please switch over to this strategy for the future.

**Comment by zewa666** [comment]
You are absolutely right, sorry about that. The reason though why I'm doing this here is that its easier for me to keep development active. As soon as this gets moved to the official repo that will stop of course. Sry for any inconveniences you experienced
