### ISSUE TITLE
issue with 0.6.0 release

### ISSUE THREAD

**Issue by samlin99** [zewa666/aurelia-i18next#34]
After updated to release version 0.6.0, I got this error starting up Aurelia application. 

Unhandled promise rejection TypeError: config.globalResources is not a function
    at y.configure (http://localhost:9000/jspm_packages/github/zewa666/aurelia-i18next@0.6.0/index.js:69:12)

![capture_1](https://cloud.githubusercontent.com/assets/12260974/9359736/303e98be-4658-11e5-960e-3318417747ad.JPG)

**Comment by zewa666** [comment]
That indicates that you haven't upgraded to the latest version of the aurelia framework, is that right? The API for globalizeResources changed to globalResources

**Comment by samlin99** [comment]
used to be "aurelia-framework": "github:aurelia/framework@^0.13.1",
and I upgrade to "aurelia-framework": "github:aurelia/framework@^0.15.0",

Still not working.

**Comment by zewa666** [comment]
just make sure to update all the other top-level dependencies as well. I've tested this with the recent Aurelia Navigation Skeleton App and it works as expected

**Comment by samlin99** [comment]
Issue fixed after upgrade aurelia packages. Thanks!
