### ISSUE TITLE
translation.JSON 404 not found (when deployed on server)

### ISSUE THREAD

**Issue by flieks** [zewa666/aurelia-i18next#35]
i got this error
![Image of Yaktocat](https://files.gitter.im/flieks/ywhw/blob)

**Comment by flieks** [comment]
add this to your web.config:
```
<staticContent>
      <mimeMap fileExtension=".json" mimeType="application/json" />
 </staticContent>
```

**Comment by zewa666** [comment]
As a side note ... this applies to hosting via IIS and .NET

**Comment by flieks** [comment]
true, i updated the title
