### ISSUE TITLE
Router.Title translations for the title of the page

### ISSUE THREAD

**Issue by steamonimo** [zewa666/aurelia-i18next#37]
In the router configuration you can give a title to the route:

`config.map([ { route: ['xy'], name: 'xy', moduleId: 'xy', title: 'MenuXy' } ... ]`

This route can be translated by i18n in the HTML code - for example for a nav bar

`<li repeat.for="row of router.navigation" class="${row.isActive ? 'active' : ''}">`
`<a href.bind="row.href" t="${row.title}">${row.title}</a>`
`</li>`

However the browser title of the tab/page will still be 'MenuXy'. Aurelia should adjust the behaviour of the title such that it will be translated too. It is no option to directly translate in the config phase because the language can be switched dynamically.

**Comment by zewa666** [comment]
could you please post this over at the [official repository](https://github.com/aurelia/i18n)?
