### ISSUE TITLE
aurelia-i18next not found!

### ISSUE THREAD

**Issue by inluxc** [zewa666/aurelia-i18next#7]
I get this error when i do  jspm install aurelia-i18next.

err  Repo jspm:aurelia-i18next not found!

**Comment by zewa666** [comment]
Hi, currently this is not an official repo to keep development iterations easier for me. As soon as it's done and was verified it will get moved.

In the meantime please install it like this: `jspm install github:zewa666/aurelia-i18next`

**Comment by inluxc** [comment]
I followed your instructions and i get the following error:
```
2015-04-21 17:46:26.111es6-module-loader.src.js:2605 GET http://10.100.0.5:9000/dist/aurelia-i18next.js 404 (Not Found)
2015-04-21 17:46:26.114index.js:184 Uncaught Error loading "aurelia-i18next" at http://10.100.0.5:9000/dist/aurelia-i18next.js
Error loading "aurelia-i18next" from "main" at http://10.100.0.5:9000/dist/main.js
Not Found: http://10.100.0.5:9000/dist/aurelia-i18next.jsindex.js:184 (anonymous function).
```
