### ISSUE TITLE
Error in installation 

### ISSUE THREAD

**Issue by inluxc** [zewa666/aurelia-i18next#8]
I followed your instructions and i get the following error:

2015-04-21 17:46:26.111es6-module-loader.src.js:2605 GET http://10.100.0.5:9000/dist/aurelia-i18next.js 404 (Not Found)
2015-04-21 17:46:26.114index.js:184 Uncaught Error loading "aurelia-i18next" at http://10.100.0.5:9000/dist/aurelia-i18next.js
Error loading "aurelia-i18next" from "main" at http://10.100.0.5:9000/dist/main.js
Not Found: http://10.100.0.5:9000/dist/aurelia-i18next.jsindex.js:184 (anonymous function).

**Comment by JeroenVinke** [comment]
I was able to fix this by changing 2 lines.

in config.js change
```
"zewa666/aurelia-i18next": "github:zewa666/aurelia-i18next@master",
```
to
```
"aurelia-i18next": "github:zewa666/aurelia-i18next@master",
```

and in your vm change

```
import {I18N} from 'zewa666/aurelia-i18next';
```
to
```
import {I18N} from 'aurelia-i18next';
```

**Comment by zewa666** [comment]
@JeroenVinke that's the described way yep. Wonder how you got that name prefix in there ... strange :)

**Comment by JeroenVinke** [comment]
@zewa666 The same thing was happening in the validation  plugin: https://github.com/aurelia/validation/issues/12

**Comment by zewa666** [comment]
@JeroenVinke thanks for the hint ... I hope it will get solved once moved to the official repo. That way one can install it directly via jspm registry instead of the GitHub registry.
